### ISSUE TITLE
I can't run your code

### ISSUE THREAD

**Issue by happyAmanda** [NonvolatileMemory/AAAI_2019_EXAM#2]
could  you please update the "readme.md"?

**Comment by happyAmanda** [comment]
could you please update your full code?

**Comment by NonvolatileMemory** [comment]
sorry for late reply, where is the mistake?
I am busying for EMNLP coming, so the readme can not be updated now.
But the code is very clear, I think it may not so hard to run.

**Comment by happyAmanda** [comment]
你可以提供一下数据处理的思路吗？
我用你的程序跑ag数据集跑不通
你是事先把csv里面的英文文本数据转换为词典中对应的ID了吗？

**Comment by NonvolatileMemory** [comment]
数据处理直接用的region embedding那篇文章里面的代码，你可以去看看，iclr 18的，我cite他了

**Comment by happyAmanda** [comment]
收到！谢谢~大佬加油！

在2019年4月10日 14:56，Cunxiao Du<notifications@github.com><mailto:notifications@github.com> 写道：

数据处理直接用的region embedding那篇文章里面的代码，你可以去看看，iclr 18的，我cite他了

**Comment by NonvolatileMemory** [comment]
多谢你的支持，close this issue
