### ISSUE TITLE
Check failed: shape_.Size() == shape.Size() 求助

### ISSUE THREAD

**Issue by MenglinLu** [NonvolatileMemory/AAAI_2019_EXAM#5]
请问下用自己的数据一直报Check failed: shape_.Size() == shape.Size() (188416 vs. 180224) NDArray.Reshape: target shape must have the same size as current shape when recording with autograd.是什么问题呢

**Comment by MenglinLu** [comment]
已经解决啦，batch size要设置为可以被总数据量可以整除的才可以直接跑

**Comment by NonvolatileMemory** [comment]
抱歉之前没有check 这个repo, 谢谢反馈! 加油
